[package]
name = "rutin-tizen-example"
version = "0.1.0"
authors = ["Anderson Danilo <contact@andersondanilo.com>"]
edition = "2018"

[dependencies]
rutin-tizen = "0.1.0"

[patch.crates-io]
rutin-tizen = { path = "../rutin-tizen" }
rutin-tizen-sys = { path = "../rutin-tizen-sys" }
